---
- name: uninstall old version of nodejs and npm
  yum:
    name: "{{ item }}"
    state: absent
  with_items:
    - nodejs
    - npm
  when: node_remove_installed|default(false)|bool

- name: setup nodesource repo
  shell: "{{ node_install_cmd }}"
  register: noderepo_output

- debug:
    msg: "{{ noderepo_output.stdout_lines }}"

- name: install nodejs on RedHat
  yum:
    name: nodejs
    state: present
  when:
    - ansible_os_family == 'RedHat'

- name: install nodejs on Debian
  apt:
    name: nodejs
    state: present
    update-cache: true
  when:
    - ansible_os_family == 'Debian'   

- name: install npm packages
  npm:
    name: "{{ item }}"
    state: present
    global: yes
  with_items:
    - bower
    - yarn
